### ISSUE TITLE
jquery preventDefault fails for forms when browser is set to firefox

### ISSUE THREAD

**Issue by will** [jarib/celerity#1]
http://gist.github.com/130364

The forum should not submit because of either the event.preventDefault() or by returning false. In real safari or firefox, this works ( see http://uiuc.us/jquery.html ), but when the browser on htmlunit is set to firefox, the forum submits and goes to google. When it is set to internet_explorer, it works correctly.

I'm not sure if this is a bug in celerity or htmlunit itself.

**Comment by jarib** [comment]
This was a bug in HtmlUnit. The fixed version was added to Celerity in 83d69 and is part of version 0.0.6.11.
