### ISSUE TITLE
Container#td as alias for Container#cell

### ISSUE THREAD

**Issue by ashmoran** [jarib/celerity#10]
It would be useful if you could access table cells via a `Container#td` method.  Every single time I access table cells I write `td` and wonder why it doesn't work.

It could display a warning or something if the reason for this is Watir-compatibility.

**Comment by jarib** [comment]
Alias Container#td{,s} -> Container#cell{,s}. Closed by ce7a3d2c87ff97d9e22173239077e9cf797e7478.
