### ISSUE TITLE
Element#== returns false for the same page element

### ISSUE THREAD

**Issue by ashmoran** [jarib/celerity#11]
The following code outputs "false"

```
#!/usr/bin/env jruby

require "rubygems"
gem "celerity"
require "celerity"

b = Celerity::Browser.new
b.goto("http://www.google.co.uk/")
puts b.button(:text => "Google Search") == b.button(:text => "Google Search")
```

This caught us out because we were writing Cucumber step matchers, and the code was failing even though we were actually finding the right element.  (We wanted to check that the element with input focus was the first text field in a form.)

Would it be possible to implement Element#== in terms of something with more page semantics, such as the XPath of the elements?

**Comment by jarib** [comment]
Use Element#xpath for element equality. Closed by a6a09161ab1536104d523a3103f3a7c039a992c1.
