### ISSUE TITLE
Clicking link with URL-encoded href fails (double-encoding)

### ISSUE THREAD

**Issue by kerryb** [jarib/celerity#12]
When I call `click` on a link which has a URL-encoded href (eg a link to a URL containing spaces encoded as %20), celerity appears to re-encode the URL, so for example "foo%20bar" becomes "foo%2520bar".

This was working OK in 0.7.3, but seems to have broken in 0.7.4. I'm not sure whether it's an issue with Celerity itself, or with htmlunit.

The issue can be reproduced with the following code:

```
require "rubygems"
require "celerity"

browser = Celerity::Browser.new
browser.goto('http://localhost/celerity_test.html')

browser.link(:text, 'Another page').click
puts browser.text
```

'celerity_test.html' contains the following:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head><title>Celerity Test</title></head>
  <body>
    <p>
      <a href="another%20page.html">Another page</a>
    </p>
  </body>
</html>
```

'another page.html' just needs to have some content to indicate that it's the right page.

I tried to create a patch (or at least a failing spec), but doing something similar to the above from within a spec seemed to work OK. Maybe it's fixed in master.

**Comment by jarib** [comment]
Definitely an HtmlUnit issue. Please try the current HEAD and report to their bug tracker if the problem persists.
