### ISSUE TITLE
proxy with authentication 

### ISSUE THREAD

**Issue by flagman** [jarib/celerity#13]
Is there any way to use celerity wtih proxy that uses authentication.
I just need setup login and password for Celerity::Browser.

**Comment by jarib** [comment]
Please use the mailing list for support requests.

You should look at the documentation for Celerity::Browser#initialize (to specify proxy) and Celerity::Browser#credentials= for basic HTTP authentication.

http://celerity.rubyforge.org/yard/Celerity/Browser.html#initialize-instance_method
http://celerity.rubyforge.org/yard/Celerity/Browser.html#credentials%3D-instance_method

**Comment by flagman** [comment]
Celerity::Browser#credentials= is for basic HTTP authentication, but not for PROXY authentication. 
But i have found workaround 

```
browser.webclient.getCredentialsProvider.addProxyCredentials("login", "password")
```

**Comment by jarib** [comment]
Ah, I see. 

It would be nice if the user could specify this as part of the proxy option on the constructor, i.e.

Browser.new(:proxy => "login:password@host:port")

If you decide to fork Celerity and implement this, I'd be happy to pull it in. :)
