### ISSUE TITLE
Bug in Browser#confirm

### ISSUE THREAD

**Issue by mcmire** [jarib/celerity#14]
Hi there,

I'm getting an error when I try to call Browser#confirm -- wrong number of arguments (2 for 1), pointing to the last line. It seems that it should be `listener.remove_listener(:confirm, &blk)` and not `listener.remove_listener(:confirm, blk)`.

Thanks,
-- Elliot

**Comment by mcmire** [comment]
Gah! Ignore this. I had a version of the old Github gem installed which it seems was conflicting with the Gemcutter version.

**Comment by jarib** [comment]
Ok, closing this.
