### ISSUE TITLE
pixel tracking with celerity

### ISSUE THREAD

**Issue by thirdreplicator** [jarib/celerity#18]
Is it possible to monitor asynchronous calls to other servers?  For example, I want to test to make sure our API is being properly implemented on a partner site: 'notify' signals are to be sent to my company's site.  I want to log that their JQuery is generatign the 'notify' signals.  There are no changes to the browser.  The signal is just a request for a pixel on my company's server with a bunch of GET params set which contains all the tracking info.  Is this possible to test using Celerity?

**Comment by jarib** [comment]
Please use the issue tracker for bugs only. Your question will be seen by more people if asked on the mailing list:

  http://rubyforge.org/pipermail/celerity-users/
