### ISSUE TITLE
setTimeout with a window.location= fails to update browser.text or browser.url

### ISSUE THREAD

**Issue by mrship** [jarib/celerity#2]
Using [this HTML](http://gist.github.com/148468) and [this ruby](http://gist.github.com/148471) the page fails to redirect as show by the url output.

If a manual page refresh is inserted using browser.send :refresh_page_from_window then it does update correctly.

**Comment by jarib** [comment]
Use WebWindowListener to update the Browser's page. Closed by 87f35d585d631d008e881d9bd90186faa4f5df9a.

This is needed in case the page changes without being triggered by a user
action - e.g. <body onload="window.location='...'">
