### ISSUE TITLE
socketConnect': java.net.ConnectException: Connection refused (NativeException)

### ISSUE THREAD

**Issue by pronix** [jarib/celerity#21]
java/net/PlainSocketImpl.java:-2:in `socketConnect': java.net.ConnectException: Connection refused (NativeException)
    from java/net/AbstractPlainSocketImpl.java:310:in`doConnect'
    from java/net/AbstractPlainSocketImpl.java:176:in `connectToAddress'
    from java/net/AbstractPlainSocketImpl.java:163:in`connect'
    from java/net/SocksSocketImpl.java:384:in `connect'
    from java/net/Socket.java:546:in`connect'
    from sun/security/ssl/SSLSocketImpl.java:570:in `connect'
    from sun/security/ssl/SSLSocketImpl.java:414:in`<init>'
    from sun/security/ssl/SSLSocketFactoryImpl.java:142:in `createSocket'
     ... 16 levels...
    from ./main.rb:212
    from ./main.rb:208:in`each'
    from ./main.rb:208

211    aimb = Celerity::Browser.new(:resynchronize => true)
212    aimb.goto(AIM_LOGIN)

**Comment by jarib** [comment]
What makes you believe this is a Celerity issue and not an issue with your local environment (proxy?) or the host you're trying to connect to? What's the value of AIM_LOGIN?

If you can't provide a way reproduce the issue, I'm afraid there's not much we can do with this.

**Comment by jarib** [comment]
Closing this as no more info has been provided.
