### ISSUE TITLE
Invalid gemspec warning during "bundle install", "bundle update"

### ISSUE THREAD

**Issue by wincent** [jarib/celerity#22]
Not sure if there's anything that can be done about this one but I am seeing messages like this when doing "bundle install" or "bundle update" with Bundler 1.0.0.beta.2 and RubyGems 1.3.7 on Mac OS X 10.6.4:

```
Using celerity (0.7.9) from git://github.com/jarib/celerity.git (at master) 
celerity at /Users/wincent/.bundle/bundler/gems/celerity-f7a0796 did not have a valid gemspec.
This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
The validation message from Rubygems was:
  ["lib/celerity/htmlunit/commons-httpclient-3.1.jar", "lib/celerity/htmlunit/htmlunit-2.7-SNAPSHOT.jar", "lib/celerity/htmlunit/htmlunit-core-js-2.7-SNAPSHOT.jar", "lib/celerity/htmlunit/nekohtml-1.9.14-20100122.114035-12.jar"] are not files
```

The line in my Gemfile that I'm using is:

```
gem 'celerity', :require => nil, :git => 'git://github.com/jarib/celerity.git'
```

I think I started seeing these messages when I switched to the Git version of Celerity. Didn't see them in the last released gem.

Cheers,
Wincent

**Comment by jarib** [comment]
Please try again - 3857bf0 should fix your issue.

**Comment by wincent** [comment]
Yep, that fixes it.

To answer your commit message, "Updated gemspec - does it really need to be in git?
", yes, I think so, according to this:
- http://yehudakatz.com/2010/04/02/using-gemspecs-as-intended/
- http://yehudakatz.com/2010/04/12/some-of-the-problems-bundler-solves/

Cheers and thanks,
Wincent

**Comment by jarib** [comment]
Thanks for the links - makes sense.
