### ISSUE TITLE
ins tag support

### ISSUE THREAD

**Issue by jondruse** [jarib/celerity#24]
The ins tag (for inserted text) is supported by HtmlUnit but not Celerity.  I have a fork of Celerity with support for the ins tag added.  I'm not sure if it needs tests, it doesn't look like every single element has tests. But if I'm missing something, please let me know.  Here's the branch link.

http://github.com/centraldesktop/celerity/commits/add_ins

Thanks!

**Comment by jarib** [comment]
Thanks! I think I'll rename the plural method to inses().

PS. You're aware of GitHub's pull request mechanism?

**Comment by jarib** [comment]
For the specs, do `git submodule init && git submodule update`

**Comment by jarib** [comment]
OK. Some more comments:
- Container#inss -> #inses
- Classes in non_control_elements.rb should be ordered alphabetically
- Perhaps you could add the del element as well, while you're at it?

For tests, I know the watirspec tests are quite extensive (lots of duplication for each element), but for consistency it would be nice to at least have the corresponding files there + some tests for .exists?

Sounds reasonable?

**Comment by jondruse** [comment]
ah-hah! pull requests!  great stuff thanks.

I did notice the alphabetical ordering... thought I respected that. Inses does make more sense I think too. I think the del element will be easy.  plural is dels? deles?  Whatever you want.  Also I will run the specs and see what we get.  Thanks!

**Comment by jarib** [comment]
dels sounds best to me.

I think you respected the ordering in container.rb, but not in non_control_elements.rb

**Comment by jondruse** [comment]
closing ticket.. and will use pull request.
