### ISSUE TITLE
No way to disable JavaScript

### ISSUE THREAD

**Issue by ashmoran** [jarib/celerity#3]
HtmlUnit allows you to disable JavaScript with `WebClient.setJavaScriptEnabled(false)`.  The only way to do this in Celerity is `browser.webclient.java_script_enabled = false`.

I think this should be a Celerity::Browser constructor option and also a setter (so you can turn it on and off part way through a test).

**Comment by ashmoran** [comment]
BTW I should really say please when putting in feature requests.  It would be nice if Celerity did this, not write it now goddamit :)

**Comment by jarib** [comment]
Add ability to disable JavaScript evaluation. Closed by 251b00ddbe1c29f0bd43a24d2f73268375ce43c0.
