### ISSUE TITLE
Embedded HTML in an iframe

### ISSUE THREAD

**Issue by jozip** [jarib/celerity#35]
When I encounter HTML in the form

```
    <html>
     ...
     <body>
       ...
       <iframe>
         <html>
         ...
         </html>
       </iframe>
       ...
     </body>
     ...
    </html>
```

and then wish to extract the stuff in the embedded HTML-document in the iframe, for example using

```
    browser.element_by_xpath("//iframe").innerText
```

...innerText returns an empty string.

Bug or feature? How are you supposed to get the embedded data?

(Mind you, I use Celerity for scraping and thus have no control over the HTML.)

**Comment by jarib** [comment]
Based on your description, I can't reproduce this with the latest gem (0.8.2), or on master. Please provide a failing test case if you still think there's an issue.
