### ISSUE TITLE
Small leak: browser doesn't clear all references

### ISSUE THREAD

**Issue by SpOOnman** [jarib/celerity#36]
In method Browser::page= there is a field @object assigned when Page is get. This field isn't cleared when you call Browser::close method. There should be '@object = nil' statement added in close method.

I've run into this problem running suite with hundred test cases. Each test case uses new Browser created in setup that is closed in teardown. But I've run into OutOfMemory exception as browsers keeped references to huge objects. When you add '@object = nil' to close method - you nullify reference to huge @object and heap can clean itself.

**Comment by jarib** [comment]
Thanks for the report - I'll take a look when time permits.

In theory there should never be a need to "nullify" a reference in order for it to be garbage collected though - the @object ivar should be collected when the Browser instance is collected.

**Comment by SpOOnman** [comment]
This is special case, where browser instances are not collected. Test suite scans for test cases which scans for test_\* methods and for each of them creates setup-test-teardown tuple. As tests progress test suite keeps reference to test cases. Since @browser is a field in many test cases there are many Browser instances across suite. They are not GCed since they are still referenced.

I've wrote small program that holds reference to closed browser instances. You can take a look at the heap with and without '@object = nil' statement. Program is on pastebin: http://pastebin.com/bh9sFizD

**Comment by jarib** [comment]
This was closed by the referenced commit.
