### ISSUE TITLE
Unable to submit form using the action attribute

### ISSUE THREAD

**Issue by bkone** [jarib/celerity#38]
I'm trying to run a few tests using cucumber & celerity

The HTML code is a as follows:

<form action="/search">
<img align="absmiddle" src="/images/srch_in.gif">
            <select name="media">
                <option value="all">All</option>
                <option value="articles">Articles</option>
                <option value="blogs">Blogs</option>
                <option value="videos">Videos</option>
                <option value="slideshows">Slideshows</option>
                <option value="podcasts">Podcasts</option>                                                                              
            </select>
            <input type="text" value="" name="q" class="textbox"><input align="absmiddle" type="image" onclick="return onSearch(this.form.q.value)" src="/images/srch_bttn.gif">
</form>

I'm trying to submit the form using the following
@browser.form(:action,'/search').submit

And I get the following error
undefined method `submit' for #Celerity::Form:0xd9d6ae

**Comment by jarib** [comment]
There's no Form#submit since it's not supported in HtmlUnit. Using the same mechanism to submit the form as a user would should work fine.

**Comment by bkone** [comment]
Thanks!
I went back to simply clicking the button and it works fine.
