### ISSUE TITLE
Exception: org.apache.http.NoHttpResponseException

### ISSUE THREAD

**Issue by bkone** [jarib/celerity#39]
When I run my tests using cucumber/celerity I dont see any errors in my output file, however I see the following. all my tests are doing is just clicking through a bunch of links and navigating.

C:\my_tests>jruby -S cucumber --format html --out=results.html
Nov 4, 2010 12:42:17 PM org.apache.http.impl.client.DefaultRequestDirector execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request: The target server failed to respond
Nov 4, 2010 12:42:17 PM org.apache.http.impl.client.DefaultRequestDirector execute
INFO: Retrying request

does anyone know what is happening? Can I safely ignore this?

**Comment by jarib** [comment]
You'll have to ask the HtmlUnit guys about the details, but looks like just INFO messages - i.e. safe to ignore.

Please use the mailing list for this type of questions in the future.

**Comment by bkone** [comment]
will do. Thanks!
