### ISSUE TITLE
Support for HTML5 elements

### ISSUE THREAD

**Issue by paulwalker** [jarib/celerity#41]
including section, aside, nav, address, time, progress:

Use http://html5doctor.com/glossary/ as a reference

**Comment by jarib** [comment]
Thanks for reporting, I'll make sure these get added. 

You might want to take a look at [watir-webdriver](http://github.com/jarib/watir-webdriver), where the classes are generated from the HTML specification. It can be used with HtmlUnit through the remote WebDriver server.

**Comment by paulwalker** [comment]
Yeah, it would be nice if there were some generic methods for finding elements, but I can't seem to find them.  Even the xpath examples require a specific element it seems.  It may be my lack of knowledge...I have to deal with a pure JRuby environment, btw.

Also, are there any mouseover events available?

**Comment by jarib** [comment]
Browser#element_by_xpath does what you want. In watir-webdriver (which works great on JRuby) I also have Browser#element and Browser#elements for finding generic elements, would be nice to add that those to Celerity as well. 

Not sure what you mean by "mouseover events" being available - perhaps take this to the mailing list and explain what you're trying to achieve.

**Comment by paulwalker** [comment]
Thanks.  I took a look today at watir-webdriver and selenium-webdriver.  Is there an ability to run these in a "headless" mode without actually starting an instance of the browser UI?

**Comment by jarib** [comment]
Yes, you can use both of those libs with the remote WebDriver server, which supports HtmlUnit. More details are on the wiki:

  http://code.google.com/p/selenium/wiki/RubyBindings

This blog post also has some info on how to use watir-webdriver with HtmlUnit:

  http://watirmelon.com/2010/12/14/watir-webdriver-a-detailed-introduction/

For the future I'm keeping an eye on this:

  http://code.google.com/p/webkitdriver/

**Comment by paulwalker** [comment]
So, htmlunit is the only driver that allows headless with watir/selenium-webdriver?  So, it is not possible to run the driver headless in chrome or firefox drivers as it is with Celerity?

**Comment by jarib** [comment]
Celerity doesn't support Chrome or Firefox headlessly - it's built on HtmlUnit as well.

If you want to run a real browser headlessly, look into fake X displays like Xvfb / Xvnc.

**Comment by paulwalker** [comment]
btw, thank you for your contribution to all of this :-).  

so, when i use Celerity::Browser.new(:browser => :firefox), that is using HtmlUnit?  That is what I have been doing in my spec tests and it does not launch an instance of firefox.

**Comment by jarib** [comment]
Correct. HtmlUnit tries to emulate various browsers, including Firefox.
