### ISSUE TITLE
Browser#new(:css => false) causes ArgumentError

### ISSUE THREAD

**Issue by paulwalker** [jarib/celerity#42]
ArgumentError: unknown option {:css=>false}

The culprit is line 856 of browser.rb:

self.css                    = opts.delete(:css) if opts[:css]

which fails to delete the entry out of opts as the value is false, thus failing the if condition

consider the following as a fix:
self.css                    = opts.delete(:css) if opts.include?(:css)

**Comment by jarib** [comment]
Fixed in 156f853. Thanks for reporting!
