### ISSUE TITLE
Can I emulate a specific browser?

### ISSUE THREAD

**Issue by jimknowlton** [jarib/celerity#46]
Is there any way when creating a Celerity connection that I can present myself as a specific browser to the server (in effect tweaking the user agent)?  I have a web app that requires IE 7/8 or Firefox 3.x, so it is failing when I connect using Celerity.

Thanks.

**Comment by jarib** [comment]
Yes. Check the docs for [Browser#initialize](http://rubydoc.info/gems/celerity/0.8.6/Celerity/Browser:initialize). 

Please use the mailing list instead of the issue tracker for questions in the future.

**Comment by jimknowlton** [comment]
OK, thanks...and I will do that...sorry.
