### ISSUE TITLE
Unable to open www.yahoo.com in default/firefox mode!

### ISSUE THREAD

**Issue by mrinalkuchhal** [jarib/celerity#48]
On opening the website "http://www.yahoo.com" in default or firefox or firefox3 mode the website is not opened properly. However when I open it in internet_explorer mode the website opens properly.
I am using the latest version 0.8.7.

Here is the sample code:
<code>
require "rubygems"
require "celerity"
br = Celerity::Browser.new()
br.goto("http://www.yahoo.com")
puts br.html
</code>

Expected Output: The entire source code of the website

Actual Output: Just 1 line 
<code>
</code>
which is actually just the last line of the source code of the site.
However if I open it in internet_explorer mode

<code>
require "rubygems"
require "celerity"
br = Celerity::Browser.new(:browser => :internet_explorer)
br.goto("http://www.yahoo.com")
puts br.html
</code>
It functions as expected and the complete site is available.

**Comment by jarib** [comment]
Hi,

This isn't a bug in Celerity, but in HtmlUnit. See this page for how to submit bugs:

http://htmlunit.sourceforge.net/submittingBugs.html

This seems to be reproducible going way back through Celerity's (and HtmlUnit's history). I tried 4d322c2, which is from December 2009, and I still get the same behaviour.

Here's the JRuby script I used to reproduce:

<pre>
require "java"

Dir['lib/celerity/htmlunit/*.jar'].each do |jar|
  require jar
end

import com.gargoylesoftware.htmlunit.WebClient
import com.gargoylesoftware.htmlunit.BrowserVersion

# version = BrowserVersion::INTERNET_EXPLORER_7
version = BrowserVersion::FIREFOX_3

wc = WebClient.new(version)
page = wc.getPage(::Java::JavaNet::URL.new("http://www.yahoo.com"))
puts page.getWebResponse.getContentAsString

wc.closeAllWindows
</pre>
