### ISSUE TITLE
SelectList#select_value behaves differently than watir equivalent.

### ISSUE THREAD

**Issue by lastobelus** [jarib/celerity#5]
SUMMARY:
Celerity selects only by option label/text; watir can select by value

DESCRIPTION:
In Watir, SelectList has two methods for selecting:
select (selects by text, or label)
select_value (selects by value)

in celerity select_value is aliased to select. However, matches_option? checks the passed value only against option labels, not against option values.

EFFECT:
Tests written to select dropdown items by value (very typical in multi-language applications for example) will fail.

**Comment by jarib** [comment]
Implement SelectList#select_value. Closed by 95c292076e1d77d79d35e180905d4d629816331f.

Also updated watirspec to 4c364821.

**Comment by jarib** [comment]
Thanks for the report.
