### ISSUE TITLE
Using Array Index in Table causes ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by myungs** [jarib/celerity#51]
Trying to find values with an array index inside a table fails with an ArrayIndexOutOfBoundsException. 

```
table = @browser.table(:index, 0)
table[0][0].text
```

Causes the following:

```
NativeException: java.lang.ArrayIndexOutOfBoundsException: -1
java/util/ArrayList.java:324:in `get'
java/util/Collections.java:1154:in `get'
sun/reflect/NativeMethodAccessorImpl.java:-2:in `invoke0'
sun/reflect/NativeMethodAccessorImpl.java:39:in `invoke'
sun/reflect/DelegatingMethodAccessorImpl.java:25:in `invoke'
java/lang/reflect/Method.java:597:in `invoke'
org/jruby/javasupport/JavaMethod.java:525:in `invokeDirectWithExceptionHandling'
C:/jruby-1.6.1/lib/ruby/site_ruby/shared/builtin/java/java.util.rb:82:in `[]'
```

**Comment by jarib** [comment]
Matching the original Watir API, Celerity has 1-indexed collections. You can change this behaviour by setting

```
Celerity.index_offset = 0
```

**Comment by myungs** [comment]
Thanks for the reply that seemed to work.

A quick question, are negative index values not supported? ie: table[0][-2]?
I get the 'ArrayIndexOutOfBoundsException: -3' in that case.

Thanks
-Seho Myung

**Comment by jarib** [comment]
Yeah, we just delegate down to the Java collection. If you turn it into a Ruby array first, it should work though:

```
table[0].to_a[-2] 
```

**Comment by myungs** [comment]
Alright cool. Thanks!
