### ISSUE TITLE
This project is no longer maintained I guess

### ISSUE THREAD

**Issue by dvwright** [jarib/celerity#63]

**Comment by jarib** [comment]
That's right. I'll add that to the description. 

If you like the API, check out [watir-webdriver](https://github.com/watir/watir-webdriver).

**Comment by dvwright** [comment]
Hi Jari,

Thank you, I will.

What did you do with all your watir/celerity tests? 
Did you switch to webdriver?

(I haven't looked at the API yet, is it "more or less" compatible with my existing watir/celerity code?)
(i.e. would have I luck trying to fork and update the celerity code or should I just switch to webdriver)

Many Thanks

On Thursday, January 30, 2014 1:06 PM, Jari Bakken notifications@github.com wrote:

That's right. I'll add that to the description. 
If you likethe API, check out watir-webdriver.

**Comment by jarib** [comment]
Yeah, those tests are using watir-webdriver now. It's more or less the same - check out [this comparison](https://github.com/watir/watir-webdriver/wiki/Comparison-with-Watir-1.X) with Watir 1.
