### ISSUE TITLE
Singular Container method names as synonym for { :index => 1 } or #first

### ISSUE THREAD

**Issue by ashmoran** [jarib/celerity#7]
As per discussion on the mailing list, a possible simplification of the element finder methods for unique elements.  For example:

```
@table.thead.cells
```

as a shorthand for either of:

```
@table.thead(:index => 1).cells
@table.theads.first.cells
```

**Comment by caius** [comment]
I'd say that goes against the principle of least surprise. You expect an array from `theads`, and therefore can grab the first element accordingly (either `.first` or `[0]`.) Having not run across the convention of singular methods returning the first element elsewhere, it's a little surprising.

**Comment by ashmoran** [comment]
In general I'd agree, but as I understand it, thead elements should be unique in a table.  Having to call `first` on a collection that only has one element seems redundant, and I find it more surprising!  Matter of taste, perhaps...

**Comment by caius** [comment]
Key word there is should though. Might be invalid HTML and you get a couple back. I dunno, maybe it does make sense with that justification, but I'd err on the side of verboseness personally I think.

**Comment by ashmoran** [comment]
If it makes you feel better, I wasn't proposing removing the long version ;)

I suppose theads may accidentally be non-unique, but I imagine most people using Celerity testing their own code, are in a position to fix that.  So you need the long version as a catchall, but my feeling is in general a singular `thead` would work.

**Comment by jarib** [comment]
Singular container method names as synonym for { :index => 1 } or #first. Closed by 61aa00289b385c97dd8787e34a3c462cd53b19a1.

**Comment by ashmoran** [comment]
Cool! Thanks.

**Comment by jarib** [comment]
Sorry it has taken so long. I was a little reluctant to add this since it's not in Watir, but it doesn't break backwards compatibility and is really a quite nice feature.
