### ISSUE TITLE
browser.remove_listener wrong number of arguments error

### ISSUE THREAD

**Issue by drogus** [jarib/celerity#9]
http://github.com/jarib/celerity/blob/master/lib/celerity/browser.rb#L533 - at this line remove_listener is called with block rather than passing it as second argument:
http://github.com/jarib/celerity/blob/master/lib/celerity/listener.rb#L52

**Comment by jarib** [comment]
Fix Browser#remove_listener. Closed by 660d799f1dcd2065576350709855af59cc9609a4.
